apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: abstracta-demo-pdb
  namespace: abstracta-tecnica
  labels:
    app.kubernetes.io/name: abstracta-demo
    environment: production
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: abstracta-demo