version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: Notas-postgres
    environment:
      POSTGRES_DB: notas-db
      POSTGRES_USER: Mauri
      POSTGRES_PASSWORD: SoyUnaPasswordRobusta
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Mauri"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: Notas-backend
    environment:
      DB_HOST: Notas-postgres
      DB_PORT: 5432
      DB_NAME: notas-db
      DB_USER: Mauri
      DB_PASSWORD: SoyUnaPasswordRobusta
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: Notas-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  pgdata: