# ─────────────────────────────────────────────
# Secret – DB credentials
# ─────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: notesdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password